apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: basic-postgres
  namespace: default
spec:
  instances: 1

  # Explicitly defining the primary bootstrap database parameters
  bootstrap:
    initdb:
      database: app
      owner: app

  storage:
    size: 1Gi
