apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
    - argoproj.io/resources-finalizer
spec:
  project: default
  source:
    repoURL: https://github.com/jacokok/argo-test
    targetRevision: HEAD
    path: bootstrap
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server-ingressroute
  namespace: argocd
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`k3s`)
      kind: Rule
      services:
        - name: argocd-server
          port: 443
          scheme: https
