apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-cluster
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:18

  storage:
    size: 1Gi
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-cluster-new
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:18
  storage:
    size: 1Gi
  bootstrap:
    initdb:
      database: club
      owner: club
      import:
        type: microservice
        databases:
          - club
        source:
          externalCluster: club
  externalClusters:
    - name: club
      connectionParameters:
        # Use the correct IP or host name for the source database
        host: doink-pc
        user: club
        dbname: club
      password:
        name: cluster-club-superuser
        key: password
