apiVersion: v1
kind: Namespace
metadata:
  name: postgres
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - argoproj.io/resources-finalizer
spec:
  destination:
    namespace: postgres
    server: https://kubernetes.default.svc
  project: default
  source:
    path: releases/
    repoURL: https://github.com/cloudnative-pg/cloudnative-pg.git
    targetRevision: main
    directory:
      recurse: false
      include: "cnpg-1.29.0.yaml"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
  info:
    - name: "Documentation: "
      value: "https://cloudnative-pg.io/documentation/current/"
