apiVersion: v1
kind: Secret
metadata:
  name: cluster-club-superuser
  namespace: postgres
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  password: "club"
---
apiVersion: v1
kind: Secret
metadata:
  name: pg-cluster-new-10-club
  namespace: postgres
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: club
  password: club
